# Makefile

.PHONY: install-dist build

run-dist:
		./build/install/app/bin/app


run:	#	Запуск
		./gradlew run

install-dist:	# Создать дистрибутив
		.gradlew installDist
		
build:	# Полная сборка проекта
		./gradlew build

clean:	# Очистка
		./gradlew clean

test:	# Тест
		./gradlew test


